apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: integration-tests-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/PTSS-Support/Integration-tests.git
        - name: revision
          value: development

    - name: run-tests
      taskRef:
        name: run-integration-tests
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - fetch-repository
